define audio.titletheme = "audio/Envision.mp3"
define audio.hyaxistheme = "audio/Almost Bliss.mp3"
define audio.alinatheme = "audio/Screen Saver.mp3"
define audio.passivetheme = "audio/Past Sadness.mp3"
define audio.interratheme = "audio/Controlled Chaos - no percussion.mp3"
define audio.relaxtheme = "audio/Fresh Air.mp3"